[bell]
animation = "EaseOutExpo"
duration = 0

[colors.bright]
black = "0x928374"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xebdbb2"
yellow = "0xfabd2f"

[colors.normal]
black = "0x282828"
blue = "0x458588"
cyan = "0x689d6a"
green = "0x98971a"
magenta = "0xb16286"
red = "0xcc241d"
white = "0xa89984"
yellow = "0xd79921"

[colors.primary]
background = "0x282828"
foreground = "0xebdbb2"

[cursor]
style = "Block"

[font]
size = 11.0

[font.bold]
family = "ComicShannsMono Nerd Font"
style = "Bold"

[font.italic]
family = "ComicShannsMono Nerd Font"
style = "Italic"

[font.normal]
family = "ComicShannsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000

[window]
title = "Alacritty"

[window.dimensions]
columns = 80
lines = 24
